### PR TITLE
Support size label customization

### LINKED ISSUE #25: Size Label Customization
### Description

Hi there! 👋  We would love the ability to customize the size labels that get applied. In our use case, it is to match previously existing capitalized labels (e.g. `size/XS`) and associated workflows with those.

### Proposal

Add new configuration options with defaults matching the existing label names:

```yaml
inputs:
  # ...
  xs_label:
    description: 'Label for xs PR'
    required: false
    default: 'size/xs'
  s_label:
    description: 'Label for s PR'
    required: false
    default: 'size/s'
  m_label:
    description: 'Label for m PR'
    required: false
    default: 'size/m'
  l_label:
    description: 'Label for l PR'
    required: false
    default: 'size/l'
# ...
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.xs_label }}
    - ${{ inputs.xs_max_size }}
    - ${{ inputs.s_label }}
    - ${{ inputs.s_max_size }}
    - ${{ inputs.m_label }}
    - ${{ inputs.m_max_size }}
    - ${{ inputs.l_label }}
    - ${{ inputs.l_max_size }}
    - ${{ inputs.fail_if_xl }}
    - ${{ inputs.message_if_xl }}
    - ${{ inputs.github_api_url }}
```

And adjusting hardcoded `size/` references in the code.

### PR DESCRIPTION
**Pull request by bflad**
Closes #25

### CODE REVIEW

**Comment by JavierCane** [comment]
Thx for the contribution!

Please, give us some time to review it. However, in order to provide quick feedback, the feature totally makes sense, so you can assume that it will be merged 😊

**Comment by ahopkins** [comment]
I am looking to add an action for labeling the size of the PR. I see there are a few options on the marketplace. Seeing this PR is about to be merged makes my decision to use this tool. Looking forward to it!

**Comment by bflad** [comment]
Pushed up fix for positional arguments to use curly braces, since anything above $9 can incorrectly expand (e.g. `$10` -> `$1` appended with a `0` character).

**Review by rgomezcasas — APPROVED** [review]
Thanks a lot and sorry for the delay reviewing it!! 👌👏

**Comment by rgomezcasas** [comment]
Released in `v1` and `v1.7.0`. Thanks!!! 😊

**Pull request merged**
